#!/bin/bash

echo "🚀 Setting up ChatMCP Database Schema"
echo "======================================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your project: desyagvwhkpjnauadwpk"
echo "3. Go to SQL Editor in the left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy the contents of supabase-migration.sql"
echo "6. Paste it into the SQL editor"
echo "7. Click 'Run' to execute the migration"
echo ""
echo "After running the migration, your database will have:"
echo "✅ conversations table"
echo "✅ messages table"
echo "✅ Row Level Security (RLS) policies"
echo "✅ Indexes for performance"
echo "✅ Real-time subscriptions enabled"
echo ""
echo "Once the migration is complete, refresh your app at:"
echo "https://chatmcp.vercel.app"
echo ""
echo "The error should be resolved and you can start creating conversations! 🎉" 