#!/bin/bash

echo "🚀 Setting up Vercel Environment Variables"
echo "=========================================="

echo ""
echo "📋 Environment Variables to add in Vercel Dashboard:"
echo ""
echo "1. Go to: https://vercel.com/thegarrettscotts-projects/web-platform/settings/environment-variables"
echo ""
echo "2. Add these variables:"
echo ""
echo "   Variable Name: NEXT_PUBLIC_SUPABASE_URL"
echo "   Value: https://desyagvwhkpjnauadwpk.supabase.co"
echo "   Environment: Production, Preview, Development"
echo ""
echo "   Variable Name: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlc3lhZ3Z3aGtwam5hdWFkd3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTM3MzAsImV4cCI6MjA2MDMyOTczMH0.eLRcvXEy5Jlj-wunr-Gy3o6Hc3hqrgKZk8L1BOqXnBA"
echo "   Environment: Production, Preview, Development"
echo ""
echo "3. After adding the variables, redeploy:"
echo "   vercel --prod"
echo ""
echo "✅ Your app will be available at:"
echo "   https://web-platform-k03e7lxir-thegarrettscotts-projects.vercel.app" 