# fly.toml app configuration file generated for chatmcp-orchestrator on 2024-01-15T21:48:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "chatmcp"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machine]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 